version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /vcf-to-gds-wf.wdl
     testParameterFiles:
         - /vcf-to-gds-terra.json
         - /vcf-to-gds-local.json
     name: vcf-to-gds-wdl
   - subclass: WDL
     primaryDescriptorPath: /ld-pruning-wf.wdl
     name: ld-pruning-wdl
   - subclass: WDL
     primaryDescriptorPath: /ld-pruning-wf.wdl
     name: ld-pruning-wdl