version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /vcf-to-gds-wf.wdl
     testParameterFiles:
         - /vcf-to-gds-terra.json
         - /vcf-to-gds-local.json
     name: vcf-to-gds-wdl
   - subclass: WDL
     primaryDescriptorPath: /king/king.wdl
     testParameterFiles:
         - /king/king-terra.json
         - /king/king-local.json
     name: king-wdl