version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /vcf-to-gds/vcf-to-gds.wdl
     testParameterFiles:
         - /vcf-to-gds/vcf-to-gds-terra.json
         - /vcf-to-gds/vcf-to-gds-local.json
     name: vcf-to-gds-wdl
   - subclass: WDL
     primaryDescriptorPath: /ld-pruning/ld-pruning.wdl
     testParameterFiles:
        - /ld-pruning/ld-pruning-terra.json
        - /ld-pruning/ld-pruning-local.json
     name: ld-pruning-wdl
   - subclass: WDL
     primaryDescriptorPath: /null-model/null-model.wdl
     testParameterFiles:
        - /null-model/null-model.json
        - /null-model/null-model-binary.json
        - /null-model/null-model-conditional.json
        - /null-model/null-model-grm.json
        - /null-model/null-model-group.json
        - /null-model/null-model-norm-bygroup.json
        - /null-model/null-model-notransform.json
        - /null-model/null-model-unrel-binary.json
        - /null-model/null-model-unrel.json
        - /null-model/terra-null-model-conditional.json
     name: null-model-wdl
   - subclass: WDL
     primaryDescriptorPath: /king/king.wdl
     testParameterFiles:
         - /king/king-terra.json
     name: king-wdl
   - subclass: WDL
     primaryDescriptorPath: /pc-relate/pcrelate.wdl
     testParameterFiles:
         - /pc-relate/pcrelate-terra.json
         - /pc-relate/pcrelate-local.json
     name: pc-relate-wdl
