version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /vcf-to-gds/vcf-to-gds.wdl
     testParameterFiles:
         - /vcf-to-gds/vcf-to-gds-terra.json
         - /vcf-to-gds/vcf-to-gds-local.json
     name: vcf-to-gds-wdl
   - subclass: WDL
     primaryDescriptorPath: /ld-pruning/ld-pruning.wdl
     testParameterFiles:
        - /ld-pruning/ld-pruning-terra.json
        - /ld-pruning/ld-pruning-local.json
     name: ld-pruning-wdl